### PR TITLE
render also water lines, fixes #7

### LINKED ISSUE #7: render linear water features - rivers and streams
Currently only water areas are rendered and in many places waterways are not yet mapped in so detailed way

### PR DESCRIPTION
**Pull request by matkoniecz**
note that rendering is the same for river and drain, with minimum zoom level as only difference (may go too far with simplification), but in my experience it works surprisingly well.

### CODE REVIEW

**Comment by ENT8R** [comment]
Maybe it is a good idea to exclude
```
tunnel=yes
```

**Comment by matkoniecz** [comment]
Can you give example of area for testing? I guess that places with long-distance tunnels for waterways would benefit, is there also other usecase?

**Comment by ENT8R** [comment]
https://www.openstreetmap.org/way/52720208/
This is another example of 
```tunnel=yes```

**Comment by westnordost** [comment]
absolutely!

**Comment by matkoniecz** [comment]
I assume that it is desirable exclude all tunnel values (except tunnel=no), including tunnel=culvert.

**Comment by matkoniecz** [comment]
PR modified.

**Comment by ENT8R** [comment]
Great! Thank you!

**Pull request merged**
