### PR TITLE
Another ENT8R->SC change

### PR DESCRIPTION
**Pull request by peternewman**
Ideally @ENT8R or someone can regenerate the JS, rather than me having to hack https://github.com/streetcomplete/streetcomplete-mapstyle/blob/gh-pages/dist/main.min.js

### CODE REVIEW

**Comment by matkoniecz** [comment]
@peternewman Have you checked that new link is actually working? It looks like something potentially actually deployed on this specific URL

**Comment by peternewman** [comment]
I hadn't, but it exists:
https://cdn.jsdelivr.net/gh/streetcomplete/streetcomplete-mapstyle@jawg/streetcomplete-dark-style.yaml

See:
https://cdn.jsdelivr.net/gh/
https://www.jsdelivr.com/?docs=gh

**Comment by ENT8R** [comment]
The change looks good so far, though I just pushed it by myself, so the final generated JS file is in the same commit as the actual change of the URL (see https://github.com/streetcomplete/streetcomplete-mapstyle/commit/4307928adb041532aa0880d94d1c9335f9220b9d).
Thank you @peternewman for fixing the links in this repository, I also changed all other links in the other branches I could find a few minutes ago.

**Comment by peternewman** [comment]
Thanks @ENT8R . Makes sense!

**Pull request closed without merging**
