### PR TITLE
Link to new server for map display

### PR DESCRIPTION
**Pull request by rugk**

### CODE REVIEW

**Comment by Akasch** [comment]
you could link to https://map-data.de/#map=17/53.59/9.93&style=streetcomplete-light for the light style. I could also import the other syles, and I propably should update them (or somebody does a pull request at https://github.com/Map-Data/map-data.de)

**Comment by ENT8R** [comment]
That would be great!

**Comment by rugk** [comment]
There are already links to https://tangram.city. Don't know who hosts this and which host may be preferred, that's @ENT8R's decimation.

**Comment by ENT8R** [comment]
But AFAIK there is no possibility to display an own mapstyle using https://tangram.city using an URL like:
https://tangram.city/tangram/view/?scene=https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/master/streetcomplete-light-style.yaml
So it would be great if the solution proposed by @Akasch would work!

**Comment by rugk** [comment]
LOL, do you know your own Readme? [In the contributing part](https://github.com/ENT8R/streetcomplete-mapstyle#contributing) you do exactly what you claimis not possible, here.

**Comment by ENT8R** [comment]
I don't see any duplicate... The ones which begin with https://tangram.city are the links to Tangram Play, the web editor for the mapstyles. The ones you want to remove are just for viewing the map without having the option to change something in the code...

**Comment by rugk** [comment]
Ah, ok. But in the editor you can also see the map, so I thought who cares to use yet another web view.

Can add the links, of course, if it's wanted.

**Comment by ENT8R** [comment]
I opened now a PR (https://github.com/Map-Data/map-data.de/pull/1) to add the other mapstyle to @Akasch's website. Would you (@rugk) like to add the links pointing to this website to the README?

**Comment by Akasch** [comment]
I have fixed a bug, so now https://map-data.de/#style=streetcomplete-dark is possible

**Comment by rugk** [comment]
@Akasch Currently no map is shown on your site: 
```
TypeError: hash is null
main.js:38:5
<anonym>
```

**Comment by ENT8R** [comment]
> I have fixed a bug, so now https://map-data.de/#style=streetcomplete-dark is possible

I think there is still a bug...

Could you try to open https://map-data.de/#style=streetcomplete-dark first and directly after that https://map-data.de/#style=streetcomplete-light ?
For me this results in still having the dark mapstyle when opening the second link...

**Comment by Akasch** [comment]
@ENT8R should be fixed, the local storage had overwritten the url

**Comment by ENT8R** [comment]
Alright. Thank you @Akasch and @rugk!

**Pull request merged**
